name: Get OIDC Token
on: workflow_dispatch  # Manually trigger the workflow

permissions:
  id-token: write      # Required to fetch the OIDC token
  contents: read

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Token
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: '100s'
  
      - name: Save Token to File
        run: |
          echo "${{ env.OIDC_TOKEN }}" > token.txt

      - name: Upload Token
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: token.txt
